# Learnable filtration with TopK auto-k vectorization and MOPED compression
# The filtration CNN is trained to transform fields in a way that maximizes Fisher information

experiment:
  name: grf_learnable_topk_moped
  output_dir: experiments/grf/results/learnable_topk_moped
  description: "GRF analysis with learnable filtration, TopK auto-k vectorization and MOPED compression"

# Load modular component files
analysis: 
  theta_fid: [1.0, 2.0]
  delta_theta: [0.1, 0.2]
  n_s: 40000
  n_d: 40000
  seed_cov: 42
  seed_ders: [43, 44]

simulator: simulators/grf.yaml
filtration: filtrations/learnable.yaml  # Learnable CNN filtration
vectorization: vectorizations/topk_auto.yaml  # Auto-k selection
compression: compressions/moped.yaml  # Analytical MOPED compression

# Training configuration for learnable filtration
training:
  n_epochs: 1000
  lr: 1.0e-3
  batch_size: 500
  weight_decay: 1.0e-4
  train_frac: 0.875
  val_frac: 0.0625
  validate_every: 10
  verbose: true